# config.toml
[default]
output_path = "content/audio"
audio_only = true
batch_size = 3
batch_delay = 1200
summary_interval = 300
model = "together_ai/meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo"
database_path = "youtube_playlists.db"
